version: "3.8"
services:
  environment:
    build: .
    container_name: picpay_transactions_application
    volumes:
      - ../:/var/www/html/
    environment:
      RABBITMQ_SERVER: rabbitmq
      DB_HOST: mysql
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public/
    depends_on:
      - rabbitmq
      - mysql
    links:
      - rabbitmq
      - mysql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: picpay_transactions_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  mysql:
    image: mysql:5.7
    container_name: picpay_transactions_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'picpay_transactions'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./init:/docker-entrypoint-initdb.d

